site_name: My Notes
theme:
  name: material
  language: zh
  features:
    - navigation.expand         # 左侧导航默认展开
    - navigation.top            # 回到顶部
    - toc.follow                # 右侧目录跟随滚动
    - toc.integrate             # 右侧目录更“像文档”
    - search.suggest            # 搜索提示
    - search.highlight          # 搜索高亮
    - content.code.copy         # 代码复制按钮

nav:
  - 首页: index.md

  - 计算化学导论:
      - 课程主页: 计算化学导论/index.md

  - 结构II：分子谱学:
      - 课程主页: 结构II：分子谱学/index.md

  - 数据结构基础:
      - 课程主页: 数据结构基础/index.md

  - 物理化学I:
      - 课程主页: 物理化学I/index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # 数学公式支持（写 LaTeX 必备）
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
